rootProject.name = "GenericSystemDesign"

include(":elevator-system")
include(":parking-lot")
include(":vending-machine")
include(":atm-machine")
include(":traffic-light")
include(":chess-game")
include(":board-game")
include(":card-game")
include(":movie-booking")
include(":hotel-reservation")
include(":flight-booking")
include(":shopping-cart")
include(":food-delivery")
include(":library-management")
include(":ride-sharing")
include(":vehicle-rental")
include(":social-media-feed")
include(":notification-system")
include(":expense-sharing")
include(":expense-tracker")
include(":url-shortener")
